### ISSUE TITLE
Android X

### ISSUE THREAD

**Issue by ravirajjak** [hsmnzaydn/image-zoom-view#2]
Doesnt Support Androidx 
App Crashes with following logs:
Process: com.xxxx.app, PID: 30318
    java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to androidx.fragment.app.FragmentActivity
        at ozaydin.serkan.com.image_zoom_view.ImageViewZoom.onClick(ImageViewZoom.java:131)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by shailevy2** [comment]
+1

**Comment by hsmnzaydn** [comment]
Fixed version at 1.3.0
